language: android
android:
  components:
     - platform-tools
     - tools
     - build-tools-23.0.2
     - android-23
     - extra-android-m2repository
     - extra-android-support
     - extra-google-m2repository
     - sys-img-armeabi-v7a-android-21
     - extra-google-google_play_services


ulimit: -s 1082768  # Require a bit of more memory.

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew assembleDebug